targets:
  $default:
    builders:
      generator|todo_reporter:
        enabled: true

builders:
  todo_reporter:
    target: ":generator"
    import: "package:generator/builder.dart"
    builder_factories: ["todoReporter"]
    build_extensions: {".dart": [".todo_reporter.g.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]